SELECT
    (2 + 3) AS SUMA,
    (2 - 3) AS RESTA,
    (2 * 3) AS MULTIPLICACION,
    (2 / 3.0) AS DIVISION,
    (5 % 2) AS MODULO,
    (|/ 25.0) AS RAIZ_CUADRADA,
    POWER(27.0,
    1.0 / 3.0) AS RAIZ_CUBICA,
    (120) AS FACTORIAL,
    ABS(-5.0) AS VALOR_ABSOLUTO,
    (91 & 15) AS BITWISE_Y,
    (32 | 3) AS BITWISE_O,
    (17 # 5) AS XOR_BIT_A_BIT,
    (~ B'1100') AS NO_BIT_A_BIT,
    (1 << 4) AS DESPLAZAMIENTO_BIT_A_LA_IZQUIERDA, (8 >> 2)
    AS DESPLAZAMIENTO_BIT_A_LA_DERECHA;